# Site settings
title: "Alex Dunn"
description: "Built with Jekyll."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile*
  - node_modules/
  - vendor/

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Alex Dunn"
resume_title:                   "Software Developer"
resume_contact_email:           "alex@aadunn.ca"
resume_header_location:         "Montréal, Quebec, Canada"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        true

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true # certifications

# Resume social links
resume_social_links:
  resume_github_url:            "https://github.com/aadunn"
  resume_linkedin_url:          "https://www.linkedin.com/in/adunnn/"
  # resume_website_url:           "http://www.aadunn.ca"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Resume content
resume_summary: "Software developer providing 6 years of professional experience in API development and full-stack web development. I am excited for the opportunity to learn something new and to hone existing skills.\nI spend my personal time shooting photos with film cameras and playing the drums."
resume_experience:
  - company: "Swarmio Media Inc."
    title: "Senior Software Engineer"
    date: "January 2020 &mdash; Present"
    action_items:
      - "Developing GraphQL microservices to query and manipulate user data in support of web applications."
      - "Utilizing languages and technologies such as Scala, Java, GraphQL, MongoDB, Kubernetes, among others."
      - "Providing support and training to coworkers and new hires to grow our software team's abilities."
  - company: "Tutor"
    date: "January 2020 &mdash; Present"
    action_items:
      - "Providing support and guidance for students taking programming classes at a post-secondary level."
      - "Preparing lesson plans using my student's assignments to provide relevant and personalized guidance."
  - company: "Liberated Networks"
    title: "Software Developer"
    date: "May 2018 &mdash; October 2019"
    action_items:
      - "Developing a real-time ticketing and project management web application for St. John Energy while communicating with the client to understand a meet solution requirements."
      - "Extending and maintaining inventory systems for Bell Canada used to manage nationwide assets and data."
      - "Developing with C#, Java, JavaScript, Angular, WebSocket, Python, MySQL, MSSQL, MongoDB, and more."
  - company: "Gracenote Inc."
    title: "Full Stack Software Developer (Co-op)"
    date: "September 2016 &mdash; December 2016, May 2018 &mdash; September 2018"
    action_items:
      - "Developing GHOSTS, a RESTful API in Node.js to serve, filter, and sort sports data from a MongoDB database."
      - "Developing embeddable, interactive widgets to display sports data served from API with a mobile first design."

resume_education:
  - school: "Dalhousie University"
    title: "Bachelor of Computer Science"
    date: "Class of 2019"
resume_skills:
  - title: "Back-end Development"
    description: ""
    technologies:
      - "Scala"
      - "Java"
      - "GraphQL"
      - "REST"
      - "MongoDB"
      - "MySQL"
  - title: "Web Development"
    description: ""
    technologies:
      - "JavaScript, TypeScript"
      - "NodeJS"
      - "Jekyll"
      - "CSS Preprocessors (Sass, Less)"
  - title: "Continuous Integration / Deployment"
    description: ""
    technologies:
      - "Docker"
      - "Kubernetes"
      - "GCP"
      - "AWS"
      - "ArgoCD"
      - "Gitlab Pipelines"
      
      